# Generated by Django 3.1.7 on 2021-03-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210327_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='designatedcourses',
            name='designated_courses',
            field=models.ManyToManyField(to='catalog.Course'),
        ),
    ]
