# Generated by Django 3.1.7 on 2021-03-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_designatedcourses_designated_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='meeting_day',
            field=models.CharField(choices=[('M', 'M'), ('T', 'T'), ('W', 'W'), ('R', 'R'), ('F', 'F'), ('MW', 'MW'), ('MWF', 'MWF'), ('TR', 'TR'), ('MTWRF', 'MTWRF')], max_length=10),
        ),
    ]
