# Generated by Django 3.1.7 on 2021-04-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20210406_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedtime',
            name='reserved_Day',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday')], default='', max_length=10),
        ),
    ]
