# Generated by Django 3.1.7 on 2021-04-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedtime',
            name='reserved_Day',
            field=models.CharField(choices=[('M', 'M'), ('T', 'T'), ('W', 'W'), ('R', 'R'), ('F', 'F'), ('MW', 'MW'), ('MWF', 'MWF'), ('TR', 'TR'), ('MTWRF', 'MTWRF')], default='', max_length=10),
        ),
    ]
