# Generated by Django 3.1.7 on 2021-04-12 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_auto_20210411_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservedtime',
            name='reserved_Day',
            field=models.CharField(choices=[('M', 'M'), ('T', 'T'), ('W', 'W'), ('R', 'R'), ('F', 'F')], default='', max_length=10),
        ),
    ]
