# Generated by Django 3.1.7 on 2021-04-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_scheduledcourses_scheduleoption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledcourses',
            name='scheduleOption',
        ),
        migrations.AddField(
            model_name='scheduledcourses',
            name='groupNumber',
            field=models.IntegerField(default=0),
        ),
    ]
