# Generated by Django 3.1.7 on 2021-04-14 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20210414_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleoption',
            name='scheduled_Courses',
            field=models.ManyToManyField(to='catalog.ScheduledCourses'),
        ),
    ]
