# Generated by Django 3.1.7 on 2021-04-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_scheduleoption_scheduled_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='sections',
        ),
        migrations.AddField(
            model_name='schedule',
            name='savedScheduledCourse',
            field=models.ManyToManyField(to='catalog.ScheduledCourses'),
        ),
    ]
